# Generated by Django 5.2.9 on 2025-12-02 17:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Your thoughts to share with the world')),
                ('author_name', models.CharField(blank=True, help_text='Your name (leave blank to post anonymously)', max_length=100, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='notes_note_created_067654_idx'), models.Index(fields=['is_anonymous'], name='notes_note_is_anon_f7dd42_idx')],
            },
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Your response to this thought')),
                ('author_name', models.CharField(blank=True, help_text='Your name (leave blank to reply anonymously)', max_length=100, null=True)),
                ('is_anonymous', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='notes.note')),
            ],
            options={
                'verbose_name_plural': 'Replies',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['created_at'], name='notes_reply_created_502c2a_idx'), models.Index(fields=['is_anonymous'], name='notes_reply_is_anon_95bc6e_idx'), models.Index(fields=['note', 'created_at'], name='notes_reply_note_id_511c07_idx')],
            },
        ),
    ]
